### ISSUE TITLE
Section 2 Challenges typo?

### ISSUE THREAD

**Issue by RayKoopa** [jeffThompson/CollisionDetection#12]
Not using Processing, but task 2 in the Section 2 challenges sounds like a copy paste error:
> "As noted, these examples assume the default `rectMode(CENTER)`. Can you make new versions to work with `rectMode(CENTER)` instead?"

Pretty sure you wanted to name another `rectMode` there.

**Comment by jeffThompson** [comment]
Oops, thanks for catching that! Fixed now.
