### ISSUE TITLE
Circle Polygon Collision, corners are not detected

### ISSUE THREAD

**Issue by Hn5624** [jeffThompson/CollisionDetection#2]
The circle can enter halfway into the polygon undetected if you start from the very tip of the vertexes.
Sorry i do not know mathematics well enough to phrase it more exact, although it is very easy to find if you play with it a little.

**Comment by jeffThompson** [comment]
You're right! It's weird, since the Line/Circle code works just fine at the ends. If you find a solution, let me know, otherwise I'll have to dig into this when I have a bit more time.

**Comment by Hn5624** [comment]
Ill try to see if its a bug, although I'm very tempted to just patch it by using  Circle to Circle collision for the vertices.

**Comment by jeffThompson** [comment]
Circle/point would do the trick, and should be pretty fast.

**Comment by Hn5624** [comment]
Found the reason.
The line/Circle WebPage checked if the points are inside the circle.
however, the polygon/Circle WebPage did not check if the points of the line segment are inside the circle.

    var inside1 = pointCircle(x1,y1, cx,cy,cr);
    var inside2 = pointCircle(x2,y2, cx,cy,cr);
    if (inside1 || inside2) return true;

The circle polygon collision was missing this code in the function

boolean lineCircle(float x1, float y1, float x2, float y2, float cx, float cy, float r)

**Comment by jeffThompson** [comment]
Nice catch! That's what happens when you have too many versions of your code lying around. Should be fixed now!
