### ISSUE TITLE
"LINE/RECTANGLE" article has incorrect title

### ISSUE THREAD

**Issue by Peter-Schorn** [jeffThompson/CollisionDetection#28]
The [LINE/RECTANGLE](http://www.jeffreythompson.org/collision-detection/line-rect.php) article has an incorrect title. It's really about the collision of a rectangle and line *segment*. Please update the article accordingly. It's really annoying to scour the internet for how to determine the intersection between a line and a rectangle and discover articles with this kind of title but which are really about the collision between a line segment and rectangle.

**Comment by Peter-Schorn** [comment]
In fact, now that I've reviewed the table of contents, almost every article that mentions lines is really about line segments.

**Comment by jeffThompson** [comment]
I think there's a difference between what most people think of as a line and what you describe. For sure, line segment is more accurate in the same way a box of generic tissues aren't actually Kleenex, but we all know what's meant when someone calls a box of tissues by the brand name. The audience for this resource is beginners, so I'm going to leave it as is to be simple and clear. There's a note on the first line example saying that technically we're talking about line segments, to avoid confusion.
