### ISSUE TITLE
Point/Point have a typo error?

### ISSUE THREAD

**Issue by thiagola92** [jeffThompson/CollisionDetection#6]
> Note the bit of shorthand above: we could specify `else { return true; }`

Shouldn't be `else { return false; }`?

**Comment by GoToLoop** [comment]
Actually, if it's either `true` or `false`, simply return the conditional expression: :P
```java
boolean pointPoint(float x1, float y1, float x2, float y2) {
  return x1 == x2 && y1 == y2;
}
```

**Comment by jeffThompson** [comment]
Nice catch @thiagola92 – thanks!

@GoToLoop – true but I wanted to make this text and the code as easy to understand as possible. If statements like that take me some time to get my head around, and I (would guess) there's probably no performance gains doing it that way.

**Comment by LuckyWindsck** [comment]
@jeffThompson 
Thank you for fixing this typo, but it seems that this problem still exists.

# Problem
I saw the fix in this commit (https://github.com/jeffThompson/CollisionDetection/commit/8e995b3772b9a664f50b9456846b07a1d3a72675).
![image](https://user-images.githubusercontent.com/24631178/131232722-8356202d-f123-471a-a0e9-a3ed04831bb7.png)

However, it still shows `true` on the website (https://www.jeffreythompson.org/collision-detection/point-point.php).
![image](https://user-images.githubusercontent.com/24631178/131232673-a309c26e-a5e2-420f-ab7f-9226a5e37112.png)

# Note
I've also notice that the fix in a later commit (https://github.com/jeffThompson/CollisionDetection/commit/cc437a08e62a831d0acdfec32af2f00095d19224) has been updated onto the website (https://www.jeffreythompson.org/collision-detection/object_oriented_collision.php). So, I am not sure why the fix in the typo-fixing commit has not been applied to the website.

![image](https://user-images.githubusercontent.com/24631178/131232710-e05cc06a-5904-4791-8602-765f54585ee3.png)
![image](https://user-images.githubusercontent.com/24631178/131232713-2594e343-775f-4efe-bb67-2d2e03cc206f.png)
